services:
  node_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - devops_api_node_network

networks:
  devops_api_node_network:
    name: devops_api_node_network
    external: true